[package]
name = "siwe_pam"
version = "0.0.1"
edition = "2021"
authors = ["Abran DeCarlo <abrandecarlo@protonmail.com>"]

[lib]
name = "siwe_pam"
crate-type = ["cdylib"]

[dependencies]
pam-bindings = "0.1.1"
users = "0.11.0"
