###########################################
# Variables                               #
# directory not the same for all distros! #
###########################################
pam_module_dir := '/lib/x86_64-linux-gnu/security'
pamd_file := '/etc/pam.d/pam-siwe'

############
# Commands #
############

run: module client

#########
module:
  @cargo build --release --manifest-path=module/Cargo.toml
  sudo cp module/conf/pam-siwe {{pamd_file}}
  sudo cp ./target/release/libsiwe_pam.so \
  {{pam_module_dir}}/siwe_pam.so
  sudo chmod 755 {{pam_module_dir}}/siwe_pam.so

client:
  @cargo build --release --manifest-path=client/Cargo.toml
  ./target/release/pam-client-template
#########

clean:
  sudo rm {{pamd_file}} {{pam_module_dir}}/siwe_pam.so
